trades_data = [
    {
        "tradeId": 1,
        "customer": "Wall Bentley",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 132,
        "unitPrice": "44.47",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 2,
        "customer": "Roberts Townsend",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 121,
        "unitPrice": "26.67",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 3,
        "customer": "Wall Bentley",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 172,
        "unitPrice": "23.87",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 4,
        "customer": "Fernandez Rosario",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 194,
        "unitPrice": "156.35",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 5,
        "customer": "Hooper Day",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 137,
        "unitPrice": "70.13",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 6,
        "customer": "Josephine Walker",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 197,
        "unitPrice": "183.15",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 7,
        "customer": "Roberts Townsend",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 160,
        "unitPrice": "165.56",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 8,
        "customer": "Ashley George",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 184,
        "unitPrice": "32.22",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 9,
        "customer": "Alston Osborne",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 160,
        "unitPrice": "139.19",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 10,
        "customer": "Randi Reed",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 167,
        "unitPrice": "30.77",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 11,
        "customer": "Sutton Edwards",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 134,
        "unitPrice": "194.54",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 12,
        "customer": "Farrell Dejesus",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 157,
        "unitPrice": "56.00",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 13,
        "customer": "Kelsey Cobb",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 106,
        "unitPrice": "20.85",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 14,
        "customer": "Erna Walton",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 109,
        "unitPrice": "99.92",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 15,
        "customer": "Nola Rios",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 191,
        "unitPrice": "130.39",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 16,
        "customer": "Fernandez Rosario",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 128,
        "unitPrice": "114.15",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 17,
        "customer": "Peterson Hines",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 147,
        "unitPrice": "189.27",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 18,
        "customer": "Koch Oneal",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 133,
        "unitPrice": "121.69",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 19,
        "customer": "Hooper Day",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 104,
        "unitPrice": "90.29",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 20,
        "customer": "Nola Rios",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 124,
        "unitPrice": "84.18",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 21,
        "customer": "Nola Rios",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 148,
        "unitPrice": "44.83",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 22,
        "customer": "Fernandez Rosario",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 104,
        "unitPrice": "74.70",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 23,
        "customer": "Farrell Dejesus",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 182,
        "unitPrice": "56.97",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 24,
        "customer": "Socorro Brown",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 183,
        "unitPrice": "58.46",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 25,
        "customer": "Kelsey Cobb",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 194,
        "unitPrice": "62.23",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 26,
        "customer": "Nola Rios",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 166,
        "unitPrice": "128.41",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 27,
        "customer": "Peterson Hines",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 169,
        "unitPrice": "111.51",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 28,
        "customer": "Malone Harding",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 185,
        "unitPrice": "53.01",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 29,
        "customer": "Alston Osborne",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 154,
        "unitPrice": "46.98",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 30,
        "customer": "Koch Oneal",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 135,
        "unitPrice": "176.91",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 31,
        "customer": "Randi Reed",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 117,
        "unitPrice": "157.92",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 32,
        "customer": "Erna Walton",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 156,
        "unitPrice": "158.77",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 33,
        "customer": "Hooper Day",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 145,
        "unitPrice": "187.84",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 34,
        "customer": "Wall Bentley",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 178,
        "unitPrice": "185.65",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 35,
        "customer": "Stafford Mack",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 177,
        "unitPrice": "115.32",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 36,
        "customer": "Ashley George",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 152,
        "unitPrice": "198.40",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 37,
        "customer": "Alston Osborne",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 118,
        "unitPrice": "116.44",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 38,
        "customer": "Peterson Hines",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 132,
        "unitPrice": "184.54",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 39,
        "customer": "Kelsey Cobb",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 155,
        "unitPrice": "114.90",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 40,
        "customer": "Randi Reed",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 157,
        "unitPrice": "148.57",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 41,
        "customer": "Randi Reed",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 121,
        "unitPrice": "39.25",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 42,
        "customer": "Dorthy Sexton",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 123,
        "unitPrice": "104.12",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 43,
        "customer": "Randi Reed",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 195,
        "unitPrice": "136.82",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 44,
        "customer": "Decker Norris",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 175,
        "unitPrice": "125.04",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 45,
        "customer": "Randi Reed",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 166,
        "unitPrice": "113.86",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 46,
        "customer": "Sutton Edwards",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 194,
        "unitPrice": "166.97",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 47,
        "customer": "Randi Reed",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 103,
        "unitPrice": "124.82",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 48,
        "customer": "Nola Rios",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 103,
        "unitPrice": "84.75",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 49,
        "customer": "Josephine Walker",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 180,
        "unitPrice": "120.72",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 50,
        "customer": "Randi Reed",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 141,
        "unitPrice": "23.74",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 51,
        "customer": "Socorro Brown",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 139,
        "unitPrice": "126.15",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 52,
        "customer": "Ashley George",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 163,
        "unitPrice": "120.24",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 53,
        "customer": "Socorro Brown",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 174,
        "unitPrice": "112.92",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 54,
        "customer": "Dorthy Sexton",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 109,
        "unitPrice": "36.10",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 55,
        "customer": "Roberts Townsend",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 136,
        "unitPrice": "69.89",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 56,
        "customer": "Fernandez Rosario",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 148,
        "unitPrice": "174.87",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 57,
        "customer": "Malone Harding",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 111,
        "unitPrice": "50.64",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 58,
        "customer": "Stafford Mack",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 174,
        "unitPrice": "68.30",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 59,
        "customer": "Nola Rios",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 103,
        "unitPrice": "190.98",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 60,
        "customer": "Hooper Day",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 103,
        "unitPrice": "197.14",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 61,
        "customer": "Josephine Walker",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 104,
        "unitPrice": "198.05",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 62,
        "customer": "Malone Harding",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 100,
        "unitPrice": "121.08",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 63,
        "customer": "Wall Bentley",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 195,
        "unitPrice": "89.65",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 64,
        "customer": "Socorro Brown",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 152,
        "unitPrice": "92.26",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 65,
        "customer": "Randi Reed",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 105,
        "unitPrice": "137.00",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 66,
        "customer": "Hooper Day",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 118,
        "unitPrice": "72.00",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 67,
        "customer": "Hooper Day",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 198,
        "unitPrice": "92.11",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 68,
        "customer": "Dorthy Sexton",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 181,
        "unitPrice": "198.41",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 69,
        "customer": "Stafford Mack",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 130,
        "unitPrice": "167.45",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 70,
        "customer": "Ashley George",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 143,
        "unitPrice": "49.79",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 71,
        "customer": "Koch Oneal",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 106,
        "unitPrice": "117.50",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 72,
        "customer": "Malone Harding",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 130,
        "unitPrice": "29.76",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 73,
        "customer": "Ashley George",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 180,
        "unitPrice": "136.48",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 74,
        "customer": "Malone Harding",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 186,
        "unitPrice": "163.72",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 75,
        "customer": "Sutton Edwards",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 116,
        "unitPrice": "129.94",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 76,
        "customer": "Koch Oneal",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 103,
        "unitPrice": "105.69",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 77,
        "customer": "Dorthy Sexton",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 138,
        "unitPrice": "152.79",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 78,
        "customer": "Peterson Hines",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 156,
        "unitPrice": "196.22",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 79,
        "customer": "Wall Bentley",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 179,
        "unitPrice": "42.04",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 80,
        "customer": "Fernandez Rosario",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 194,
        "unitPrice": "180.82",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 81,
        "customer": "Randi Reed",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 118,
        "unitPrice": "119.70",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 82,
        "customer": "Kelsey Cobb",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 189,
        "unitPrice": "108.09",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 83,
        "customer": "Koch Oneal",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 161,
        "unitPrice": "67.61",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 84,
        "customer": "Hooper Day",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 177,
        "unitPrice": "187.55",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 85,
        "customer": "Peterson Hines",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 100,
        "unitPrice": "191.56",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 86,
        "customer": "Randi Reed",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 185,
        "unitPrice": "163.87",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 87,
        "customer": "Kelsey Cobb",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 153,
        "unitPrice": "145.30",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 88,
        "customer": "Malone Harding",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 158,
        "unitPrice": "152.53",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 89,
        "customer": "Erna Walton",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 158,
        "unitPrice": "146.30",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 90,
        "customer": "Socorro Brown",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 191,
        "unitPrice": "49.43",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 91,
        "customer": "Josephine Walker",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "AAL:LN",
        "securityDescription": "ANGLO AMERICAN PLC",
        "quantity": 171,
        "unitPrice": "107.72",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 92,
        "customer": "Nola Rios",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 104,
        "unitPrice": "85.14",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 93,
        "customer": "Hooper Day",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 136,
        "unitPrice": "71.28",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 94,
        "customer": "Ashley George",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 149,
        "unitPrice": "178.84",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 95,
        "customer": "Dorthy Sexton",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 125,
        "unitPrice": "183.25",
        "originalCurrency": "GBP"
    },
    {
        "tradeId": 96,
        "customer": "Stafford Mack",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "VOD:LN",
        "securityDescription": "Vodafone Group PLC",
        "quantity": 127,
        "unitPrice": "175.88",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 97,
        "customer": "Nola Rios",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 156,
        "unitPrice": "109.20",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 98,
        "customer": "Wall Bentley",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "BMW:GR",
        "securityDescription": "Bayerische Motoren Werke AG",
        "quantity": 146,
        "unitPrice": "168.54",
        "originalCurrency": "EUR"
    },
    {
        "tradeId": 99,
        "customer": "Kelsey Cobb",
        "trade": "Buy",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NTES:US",
        "securityDescription": "DSWE",
        "quantity": 198,
        "unitPrice": "61.20",
        "originalCurrency": "USD"
    },
    {
        "tradeId": 100,
        "customer": "Erna Walton",
        "trade": "Sell",
        "isin": "GB00BH4HKS39",
        "bbgSymbol": "NFLX:US",
        "securityDescription": "NETFLIX",
        "quantity": 156,
        "unitPrice": "110.28",
        "originalCurrency": "EUR"
    }
]
